# This file stores the list of databases
  oedbInstances:
  - dblocation: "localhost"
    oeinstalllocation: "/psc/dlc"
    dbname: "mttenant"
    serviceNameOrPort: "37010"
    user: "sysprogress"
    password: "sysprogress"
    currentWorkDir: "/psc/wrk"
    isAutoDiscovered: false
