name: Docker Image CI
 
on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - 
        name: Setup docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Checkout Everything again
        uses: actions/checkout@v4
          
      - name: copy file via ssh password
        uses: nicklasfrahm/scp-action@main
        with:
          direction: download
          host: ${{ secrets.AZURE_BLOBSFTP_HOST }}
          key: ${{ secrets.AZURE_BLOBSFTP_KEY }}
          fingerprint: ${{ secrets.AZURE_BLOBSFTP_FINGER }}
          username: ${{ secrets.AZURE_BLOBSFTP_USER }}
          source: /oecc/*
          target: "${{ github.workspace }}/binaries" 
        
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: "${{ github.workspace }}/agent"
          push: true
          tags: rdroge/mtpas_oecc:${{ vars.OE_VERSION }}-${{ vars.OECC_VERSION }}
          file: Dockerfile_pasoe
          
