name: Docker Image CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - 
        name: Setup docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Checkout Everything again
        uses: actions/checkout@v4
          
      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.AZURE_BLOBSFTP_HOST }}
          username: ${{ secrets.AZURE_BLOBSFTP_USER }}
          password: ${{ secrets.AZURE_BLOBSFTP_PASSWORD }}
          port: ${{ secrets.AZURE_BLOBSFTP_PORT }}
          source: "/oecc/PROGRESS_OECC_AGENT_1.3.0_LNX_64.tar.gz"
          target: "${{ github.workspace }}/binaries"      
      - name: check contents of directory
        run:
          ls ${{ github.workspace }}/binaries
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: "${{ github.workspace }}/agent"
          push: true
          tags: rdroge/mtpas_oecc:${{ vars.OE_VERSION }}-${{ vars.OECC_VERSION }}
          file: Dockerfile_pasoe
          
